## CodeAlpha

## Task 4:

## A/B Testing Analysis:

## Problem Statement:

## Conduct  an A/B analysis to evaluate the impact of a change or intervention. Analyze the results using statistical techniques and draw actionable insights

## Solution:

The goal of A/B testing in this project is to provide evidence-based insights into the effectiveness of a change or intervention and to inform decision-making processes with actionable data-driven recommendations.

## Part 1: Statistics

## Importing some important libraries

In [1]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
%matplotlib inline
random.seed(42)

## Loading the ab_data

In [2]:
df = pd.read_csv('ab_data.csv')
df.head()

user_id                   timestamp      group landing_page  converted
0   851104  2017-01-21 22:11:48.556739    control     old_page          0
1   804228  2017-01-12 08:01:45.159739    control     old_page          0
2   661590  2017-01-11 16:55:06.154213  treatment     new_page          0
3   853541  2017-01-08 18:28:03.143765  treatment     new_page          0
4   864975  2017-01-21 01:52:26.210827    control     old_page          1

## Getting the number of rows and columns

In [3]:
df.shape

(294478, 5)

In [52]:
# checking for unique records in each column
df.nunique()

user_id         290584
timestamp       290584
group                2
landing_page         2
converted            2
intercept            1
dtype: int64

In [53]:
# The proportion of users converted in the data

df['converted'].value_counts()[1] / (df['converted'].value_counts()[0] + df['converted'].value_counts()[1])

0.11959708724499628

In [6]:
# The number of times the "new_page" and "treatment" don't line up.

df.query("group == 'treatment' and landing_page != 'new_page'").count()[0] + \
df.query("group != 'treatment' and landing_page == 'new_page'").count()[0]

C:\Users\tiwar\AppData\Local\Temp\ipykernel_9328\3329623591.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.query("group == 'treatment' and landing_page != 'new_page'").count()[0] + \
C:\Users\tiwar\AppData\Local\Temp\ipykernel_9328\3329623591.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.query("group != 'treatment' and landing_page == 'new_page'").count()[0]


3893

In [54]:
# geting the information in the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 290584 entries, 0 to 294477
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype 
---  ------        --------------   ----- 
 0   user_id       290584 non-null  int64 
 1   timestamp     290584 non-null  object
 2   group         290584 non-null  object
 3   landing_page  290584 non-null  object
 4   converted     290584 non-null  int64 
 5   intercept     290584 non-null  int64 
dtypes: int64(3), object(3)
memory usage: 23.6+ MB


In [55]:
# Regrouping  with new variables in the dataset

df.drop(df.query("group == 'treatment' and landing_page != 'new_page'").index, inplace = True)
df.drop(df.query("group != 'treatment' and landing_page == 'new_page'").index, inplace = True)
df2 = df
df2.shape

(290584, 6)

In [56]:
# Check if all of the correct rows are removed - that should be 0

df2[((df2['group'] == 'treatment') == (df2['landing_page'] == 'new_page')) == False].shape[0]

0

In [57]:
# again checking for unique records
df2.nunique()

user_id         290584
timestamp       290584
group                2
landing_page         2
converted            2
intercept            1
dtype: int64

In [58]:
# Find out a duplicated from "user_id" column

df2[df2['user_id'].duplicated()]

Empty DataFrame
Columns: [user_id, timestamp, group, landing_page, converted, intercept]
Index: []

In [12]:
# The row information for the duplicated

duplicate = df2[df2['user_id'].duplicated()]

In [13]:
# Remove the duplicated

df2.drop(duplicate.index, inplace = True)

In [14]:
df2.nunique()

user_id         290584
timestamp       290584
group                2
landing_page         2
converted            2
dtype: int64

In [15]:
# The probability converted in the control group

control = df2.query("group == 'control' and converted == 1").count()[4] / df2[df2['group'] == 'control'].count()[4]
control

C:\Users\tiwar\AppData\Local\Temp\ipykernel_9328\344909776.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  control = df2.query("group == 'control' and converted == 1").count()[4] / df2[df2['group'] == 'control'].count()[4]
C:\Users\tiwar\AppData\Local\Temp\ipykernel_9328\344909776.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  control = df2.query("group == 'control' and converted == 1").count()[4] / df2[df2['group'] == 'control'].count()[4]


0.1203863045004612

In [16]:
# The probability converted in the treatment group

treatment = df2.query("group == 'treatment' and converted == 1").count()[4] / df2[df2['group'] == 'treatment'].count()[4]
treatment

C:\Users\tiwar\AppData\Local\Temp\ipykernel_9328\2350509737.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  treatment = df2.query("group == 'treatment' and converted == 1").count()[4] / df2[df2['group'] == 'treatment'].count()[4]
C:\Users\tiwar\AppData\Local\Temp\ipykernel_9328\2350509737.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  treatment = df2.query("group == 'treatment' and converted == 1").count()[4] / df2[df2['group'] == 'treatment'].count()[4]


0.11880806551510564

In [17]:
# The probability received the new page

df2.query("landing_page == 'new_page'").count()[3] / df2['landing_page'].count()

C:\Users\tiwar\AppData\Local\Temp\ipykernel_9328\3673940233.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df2.query("landing_page == 'new_page'").count()[3] / df2['landing_page'].count()


0.5000619442226688

## Part 2 A/B TESTING

In [18]:
# P_new under the null

p_new = df2.query("converted == 1").count()[4]/ df2["converted"].count()
p_new

C:\Users\tiwar\AppData\Local\Temp\ipykernel_9328\2125589424.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  p_new = df2.query("converted == 1").count()[4]/ df2["converted"].count()


0.11959708724499628

In [19]:
# P_old under the null

p_old = df2.query("converted == 1").count()[4]/ df2["converted"].count()
p_old

C:\Users\tiwar\AppData\Local\Temp\ipykernel_9328\199743315.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  p_old = df2.query("converted == 1").count()[4]/ df2["converted"].count()


0.11959708724499628

In [20]:
n_new = df2.query('group == "treatment"').count()[0]
n_new

C:\Users\tiwar\AppData\Local\Temp\ipykernel_9328\2594878698.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  n_new = df2.query('group == "treatment"').count()[0]


145310

In [21]:
n_old = df2.query('group == "control"').count()[0]
n_old

C:\Users\tiwar\AppData\Local\Temp\ipykernel_9328\853391046.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  n_old = df2.query('group == "control"').count()[0]


145274

In [22]:
p_dif = p_new - p_old
p_dif

0.0

In [23]:
# Store 1, 0 in new_page_converted 

new_page_converted = np.random.choice([0,1], n_new, p=(p_new, 1-p_new))
new_page_converted

array([1, 1, 1, ..., 1, 1, 1])

In [24]:
# Store 1, 0 in old_page_converted 

old_page_converted = np.random.choice([0,1], n_old, p=(p_old, 1-p_old))
old_page_converted

array([1, 0, 1, ..., 0, 1, 1])

In [25]:
new_page_converted.mean() - old_page_converted.mean()

-3.218463123255688e-05

In [26]:
# Apply A/B testing with statistics package

import statsmodels.api as sm

convert_old = old_page_converted.mean()
convert_new = new_page_converted.mean()

n_old = n_old
n_new = n_new

In [27]:
z_score, p_value = sm.stats.proportions_ztest(np.array([convert_new,convert_old]),np.array([n_new,n_old]), alternative = 'larger')
z_score, p_value

(-0.00018860877678137365, 0.5000752440150668)

In [59]:
from scipy.stats import norm

# Telling how significant the z-score is
norm.cdf(z_score)

0.49992475598493324

In [29]:
# Tell what the critical value at 95% confidence is

norm.ppf(1-(0.05/2))

1.959963984540054

## Part III - A regression approach

 Utilizing Logisitc Regression in this case because the response variables are Categorical Variables.

In [30]:
# Logistic Regression approach

df2['intercept'] = 1

df2 = df2.join(pd.get_dummies(df2['landing_page']))
df2['ab_page'] = pd.get_dummies(df2['group']) ['treatment']

In [31]:
df2.head()

user_id                   timestamp      group landing_page  converted  \
0   851104  2017-01-21 22:11:48.556739    control     old_page          0   
1   804228  2017-01-12 08:01:45.159739    control     old_page          0   
2   661590  2017-01-11 16:55:06.154213  treatment     new_page          0   
3   853541  2017-01-08 18:28:03.143765  treatment     new_page          0   
4   864975  2017-01-21 01:52:26.210827    control     old_page          1   

   intercept  new_page  old_page  ab_page  
0          1     False      True    False  
1          1     False      True    False  
2          1      True     False     True  
3          1      True     False     True  
4          1     False      True    False

In [39]:
print(df2.dtypes)


user_id          int64
timestamp       object
group           object
landing_page    object
converted        int64
intercept        int64
new_page          bool
old_page          bool
ab_page           bool
dtype: object


In [40]:
df2['converted'] = pd.to_numeric(df2['converted'])
df2['intercept'] = pd.to_numeric(df2['intercept'])
df2['ab_page'] = pd.to_numeric(df2['ab_page'])


In [44]:
df2.isnull().sum()

user_id         0
timestamp       0
group           0
landing_page    0
converted       0
intercept       0
new_page        0
old_page        0
ab_page         0
dtype: int64

In [47]:
 np.asarray(df2)

array([[851104, '2017-01-21 22:11:48.556739', 'control', ..., False,
        True, False],
       [804228, '2017-01-12 08:01:45.159739', 'control', ..., False,
        True, False],
       [661590, '2017-01-11 16:55:06.154213', 'treatment', ..., True,
        False, True],
       ...,
       [734608, '2017-01-22 11:45:03.439544', 'control', ..., False,
        True, False],
       [697314, '2017-01-15 01:20:28.957438', 'control', ..., False,
        True, False],
       [715931, '2017-01-16 12:40:24.467417', 'treatment', ..., True,
        False, True]], dtype=object)

In [49]:
df2['ab_page'] = df2['ab_page'].astype(int)  # Convert to integer


In [50]:
logit = sm.Logit(df2['converted'],df2[['intercept','ab_page']])

In [60]:
# Summary: Logistic Regression model  

results = logit.fit()
results.summary()

Optimization terminated successfully.
         Current function value: 0.366118
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:              converted   No. Observations:               290584
Model:                          Logit   Df Residuals:                   290582
Method:                           MLE   Df Model:                            1
Date:                Sun, 03 Mar 2024   Pseudo R-squ.:               8.077e-06
Time:                        14:03:12   Log-Likelihood:            -1.0639e+05
converged:                       True   LL-Null:                   -1.0639e+05
Covariance Type:            nonrobust   LLR p-value:                    0.1899
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
intercept     -1.9888      0.008   -246.669      0.000      -2.005      -1.973
ab_page       -0.0150      0.011     -1.311      0.190      -0.037       0.007
==============================================================================
"""